export const SET_LOADING = 'SET_LOADING'
export const SET_STORIES = 'SET_STORIES'
export const REMOVE_STORY = 'REMOVE_STORY'
export const HANDLE_PAGE = 'HANDLE_PAGE'
export const HANDLE_SEARCH = 'HANDLE_SEARCH'
export const HANDLE_TAG = 'HANDLE_TAG'
export const HANDLE_SORT = 'HANDLE_SORT'
export const HANDLE_TIME = 'HANDLE_TIME'